server:
  port: 8080

spring:
  application:
    name: Intelligent-Assistant
  datasource:
    url: jdbc:mysql://localhost:3306/Intelligent_Assistant?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          enabled: true
  ai:
    dashscope:
      api-key: ${ALIBABA_TONGYI_APIKEY}
      memory-length: 10

gaode:
  api-key: ${GAODE_TIANQI_APIKEY}
baidu:
  api-key: ${BAIDU_QIANFAN_APIKEY}
