server:
  port: 8080

spring:
  application:
    name: Intelligent-Assistant
  datasource:
    url: jdbc:mysql://localhost:3306/Intelligent_Assistant?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          enabled: true
  ai:
    dashscope:
      api-key: sk-a514564db277446fa9c551918a0c46aa
#      api-key: ${ALIBABA_TONGYI_APIKEY}
      memory-length: 10

gaode:
  api-key: c55e5d1183fdf1f66f4900e01bd26d3e
#  api-key: ${GAODE_TIANQI_APIKEY}
baidu:
  api-key: bce-v3/ALTAK-zVzCYI5NPZNaILHWXSbYF/f668dc926021ff361731cf8c3ee24a4516938d44
#  api-key: ${BAIDU_QIANFAN_APIKEY}
